# Generated by Django 5.0.6 on 2024-08-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='symptom',
            field=models.TextField(default=None),
        ),
    ]
